[project]
name = "ldx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ZackaryW", email = "36378555+ZackaryW@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
pyld = "ldx.ld_cli.__init__:cli"

[project.optional-dependencies]
pyld = [
    "click>=8.3.0",
    "psutil>=7.1.0",
]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[tool.ruff]
ignore = ["F401"]